server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/itsmproject?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: itsmdata
    password: 1234

  web:
    resources:
      add-mappings: true

mybatis:
   # 매핑 파일 경로 설정
   mapper-locations: classpath:/mapper/**/*.xml
   # 매퍼 인터페이스 패키지 위치
   type-aliases-package: hong.itsm.itsm.dto  # 도메인 클래스 위치
